id: A4F4E88E0
title: f85BF
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:47:47.689598
  last_modified_at: 2022-05-27 14:47:47.689601
