id: A4F4E88E0
title: f8777
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:47:47.690737
  last_modified_at: 2022-05-27 14:47:47.690739
