id: A4F4E88E0
title: fDC5D
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 14:47:47.697613
  last_modified_at: 2022-05-27 14:47:47.697618
